### ISSUE TITLE
Missing div?

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil-labs-website#179] opened 2016-12-14 16:24 UTC
Take a look at the right white column. It seems that there is a missing div somewhere in the welcome page.
![screenshot_20161214-131400](https://cloud.githubusercontent.com/assets/6511849/21190390/59ad6e62-c200-11e6-81f5-f405612e534f.png)

The blog page looks pretty.
![screenshot_20161214-131440](https://cloud.githubusercontent.com/assets/6511849/21190153/b27e9b16-c1ff-11e6-8495-95baf35ee78d.png)

**Comment by nathakits** [comment] 2016-12-15 10:57
Hi @cpicanco 

Thanks for the report. It is caused by the SVGs on the home page that is overflowing the site container.
This https://github.com/pupil-labs/pupil-labs-website/pull/180 should fix this problem. 

![overflow](https://cloud.githubusercontent.com/assets/17331040/21221267/587b7fc6-c2ef-11e6-97ae-f4c5dab23fab.png)

**Comment by willpatera** [comment] 2016-12-15 14:46
@cpicanco - thanks for bug report and feedback - always appreciated 😄  I believe that @nathakits's PR should have fixed the issue. I have merged #180 and it should be online shortly. 

@cpicanco - I will close this issue now, but if you still observe this behavior we can re-open. If you spot any other bugs or typos, just let us know and we will fix asap. Thanks 🙏

**Comment by cpicanco** [comment] 2016-12-15 16:35
@nathakits @willpatera 
Overflow persists on VR/AR page.
![screenshot_20161215-133258](https://cloud.githubusercontent.com/assets/6511849/21232647/1cc9ce98-c2cb-11e6-848a-991e34bba558.png)

**Comment by willpatera** [comment] 2016-12-15 23:45
@nathakits please fix this today. Also check other pages for overflow issues.

**Comment by nathakits** [comment] 2016-12-16 05:03
@cpicanco 
This overflow problem is caused by the long text on the left column. A quick fix would be to add spacing between the words, so that the words break properly and fix the overflow problem.

![localhost-3000-vr-ar- iphone 5](https://cloud.githubusercontent.com/assets/17331040/21252140/00bdd250-c387-11e6-884a-c1e783dfc8c4.png)

**Comment by willpatera** [comment] 2016-12-16 05:23
This is now fixed, but other issues exist with overflow at very small screen widths < 250px. This may be an edge case but can also be easily fixed. Separate issues / PRs can be opened for other overflow issues.

**Closed by willpatera** 2016-12-16 05:23 UTC

**Comment by cpicanco** [comment] 2016-12-16 16:21
Ps.: Prints from a 320x534 screen.

**Comment by willpatera** [comment] 2016-12-16 16:27
@cpicanco - we will add another media query break point for small screens if necessary to handle overflows. @nathakits is still working on related issues but making good progress. Should be resolved throughout the site by Monday.

**Comment by cpicanco** [comment] 2016-12-16 16:41
Great work @willpatera and @nathakits . I will review the results then.
